name: Deployment

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - run: echo 'hello build'
        shell: bash

  integration:
    runs-on: ubuntu-latest
    needs: build
    environment: integration
    name: Integration
    steps:
      - run: echo 'Deploy to Integration'
        shell: bash

  staging:
    runs-on: ubuntu-latest
    needs: integration
    environment: staging
    name: Staging
    steps:
      - run: echo 'Deploy to Staging'
        shell: bash

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment: production
    name: Production
    steps:
      - run: echo 'Deploy to Production'
        shell: bash